server:
  port: 8081

spring:
  application:
    name: patient-service
  datasource:
    url: jdbc:mysql://localhost:3306/userdb
    username: root
    password: Security@1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
