spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hospital_db
    username: root
    password: Security@1
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
